apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: ofek-cluster
  region: us-east-1

nodeGroups:
  - name: worker-nodes
    instanceType: t3.medium
    desiredCapacity: 2
    tags:
      "managedBy": "eksctl"
      "environment": "test"



